Further site list detection improvements, thanks Adeodato Simó for his suggestions.
git-svn-id: svn://anonscm.debian.org/pkg-mailman/trunk@570 153bf9da-15d3-0310-89f8-c842cf69dc3c

diff --git a/debian/mailman.init b/debian/mailman.init
--- a/debian/mailman.init
+++ b/debian/mailman.init
@@ -46,10 +46,10 @@ fi
 
 case "$1" in
   start)
-    SITE_LIST=$( grep '^MAILMAN_SITE_LIST' /etc/mailman/mm_cfg.py | cut -d"'" -f 2 )
-    [ -z "$SITE_LIST" ] && SITE_LIST='mailman'
-    if [ "$(/var/lib/mailman/bin/list_lists -b | grep ^${SITE_LIST}$ )" = "" ]; then
-        log_warning_msg "Site list for mailman (usually named mailman) missing."
+    SITE_LIST=$( sed -rne "s/^[[:space:]]*MAILMAN_SITE_LIST[[:space:]]*=[[:space:]]*(['\"])([^'\"]+)\\1/\\2/p" /etc/mailman/mm_cfg.py )
+    [ -n "$SITE_LIST" ] || SITE_LIST='mailman'
+    if ! /var/lib/mailman/bin/list_lists -b | grep -q "^${SITE_LIST}$"; then
+        log_warning_msg "Site list for mailman missing (looking for list named '${SITE_LIST}')."
         log_warning_msg "Please create it; until then, mailman will refuse to start."
         exit 0;
     fi
